### ISSUE TITLE
cannot find the code for ADKF-IFT on the MoleculeNet work benchmark

### ISSUE THREAD

**Issue by xuejunhao123** [Wenlin-Chen/ADKF-IFT#5]
Hello, where is the code for ADKF-IFT on the MoleculeNet work benchmark? I searched for a long time but couldn't find it.Can you give me some hints?

**Comment by AustinT** [comment]
Hi, we realized that this is in another repo which we have not uploaded yet. Sorry about this. We will upload it shortly.

**Comment by xuejunhao123** [comment]
Could you please remind me here after uploading? Many thx！

**Comment by xuejunhao123** [comment]
Could you please upload that code as soon as possible? I'm eager to do a comparative experiment,thank you very much!

**Comment by Wenlin-Chen** [comment]
Hi, we invited you to the repo for the moleculeNet experiments, which is based on a fork from PAR. For ADKF-IFT, you can just run the `script_train_adkf.sh`. We have not made this repo public because we don't have time to polish it yet, but we will do soon. Let us know if you have any questions.

**Comment by xuejunhao123** [comment]
thanks again
